
name: Node.js CI

# push, pull_request시 스크립트 로딩
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# 실행될 작업
jobs:
  build:

    runs-on: ubuntu-latest

	# 노드 14.x 버젼 사용
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
    
    	# 윈도우 환경과 리눅스 환경에서 충돌 회피를 위한 package-lock.json 삭제
      - name: delete package-lock.json
        run: rm package-lock.json

      - name: Install dependencies
        run: npm install

      - name: bulid file
        run: npm run build
